#!/bin/bash

# Script by Nick Gilbert (nickgilbert2@gmail.com)
# Use and modify as you will

# Checks for a running instance of openvpn, and either launches the vpn or says that it is running

# Checks for running open vpn
if ! pgrep -f 'openvpn' ; then
    # If not found, start a new one in a new terminal window
    i3-msg "exec urxvt -e bash -c ~/.bin/scripts/launch_mcecs_vpn"
else
    # if found, show the scratchpad with the vpn window
    i3-msg "[title=\"^MCECS VPN$\"] scratchpad show"
fi
