#!/bin/bash
# Check to see if htop is running, and show if it is

if ! pgrep -f 'htop' ; then
    i3-msg "exec --no-startup-id urxvt -t htop -e "htop""
    sleep 1
fi
i3-msg "[title=\"^[hH]top$\"] scratchpad show"

