#!/bin/bash

# Script by Nick Gilbert (nickgilbert2@gmail.com)
# Use and modify as you will

# Launch the vpn, and rename the window to that

function set-title() {
    echo -e "\033]0;$@\007" 
}

# go to config location
cd ~/.config/openvpn

# change title
set-title "MCECS VPN"
# go to scratchpad
i3-msg "[title=\"^MCECS VPN$\"] scratchpad show; move position 333px 0px"

# run openvpn with the config
sudo openvpn --config cecs.ovpn
