#!/bin/bash

# Script by Nick Gilbert (nickgilbert2@gmail.com)
# Use and modify as you will

# Launch arandr if it's not already running

if ! pgrep 'arandr' ; then
    i3-msg "exec arandr"
else
    i3-msg "[class=\"Arandr\"] focus"
fi
