#!/bin/bash

# Rofi wrapper for selecting the type of bars for polybar to display

if [ -f ~/.config/polybar/dyntop.var ] ; then
    top="Dynamic top -> Static top"
elif [ -f ~/.config/polybar/statictop.var ] ; then
    top="Static top -> Dynamic top"
fi

if [ -f ~/.config/polybar/dynbot.var ] ; then
    bot="Dynamic bottom -> Static bottom"
elif [ -f ~/.config/polybar/staticbot.var ] ; then
    bot="Static bottom -> Dynamic bottom"
fi

choices="${top}\n${bot}\n${top} + ${bot} (Toggle Current)\nBoth Dynamic\nBoth Static\n"
selection=$(echo -e "$choices" | rofi   -dmenu \
                                        -i \
                                        -hide-scrollbar true \
                                        -lines 5 \
                                        -p "Choose bar")
echo "$selection"

if [[ "$selection" == "$top" ]] ; then
    ~/.bin/scripts/polyswap -t
    i3-msg restart
elif [[ "$selection" == "$bot" ]] ; then
    ~/.bin/scripts/polyswap -b
    i3-msg restart
elif [[ "$selection" == "$top + $bot (Toggle Current)" ]] ; then
    ~/.bin/scripts/polyswap -t
    ~/.bin/scripts/polyswap -b
    i3-msg restart
elif [[ "$selection" == "Both Dynamic" ]] ; then
    ~/.bin/scripts/polyswap -d
    i3-msg restart
elif [[ "$selection" == "Both Static" ]] ; then
    ~/.bin/scripts/polyswap -s
    i3-msg restart
fi

