#!/bin/bash

rofi -i \
    -run-shell-command "urxvt -e /bin/bash -i -c '{cmd}';bash" \
    -modi "drun,run" \
    -show drun \
    -sidebar-mode \
    -opacity 90 \
    -width 50 \
    -separator-style "solid" \
    -font "Source Code Pro 10" \
    -no-disable-history \
    -columns 2
    #-run-list-command ". ~/.bin/scripts/alias.sh" \
    #-run-command "/bin/bash -i -c '{cmd}'" \
    #-color-enabled \
