#!/bin/bash

function checkmount()
{
    if $(findmnt | grep $1 > /dev/null); then
        echo "Mounted"
    else
        echo "Unmounted"
    fi
}

output=$(cat /etc/fstab | grep -vx "^[#U].*"  | cut -d ' ' -f 2)
for i in ${output[@]} ; do
    if [ -z $count ] ; then
        choices="$(checkmount $i) $i"
        count=1
    else
        choices="$choices\n$(checkmount $i) $i"
    fi
done
selection=$(echo -e "$choices" | rofi   -dmenu \
                                        -i \
                                        -hide-scrollbar true \
                                        -p "Network Mounts:")
mounted=$(echo "$selection" | cut -d ' ' -f 1)
selection=$(echo "$selection" | cut -d ' ' -f 2)

if [[ "$mounted" == "Mounted" ]] ; then
    umount "$selection"
    notify-send "$selection has been unmounted"
elif [[ "$mounted" == "Unmounted" ]] ; then
    mount "$selection"
    notify-send "$selection has been mounted"
fi