#!/bin/bash

# Script by Nick Gilbert (nickgilbert2@gmail.com)
# Use and modify as you will

# Starts up my tutoring shift, running the needed programs and chrome tabs in specific workspaces

i3-msg workspace 2:SLACK
i3-msg exec "google-chrome --new-window "pdx-cs.slack.com""

sleep 1

i3-msg workspace 3:CRACK
i3-msg exec "google-chrome --new-window "accounts.cat.pdx.edu""

sleep 1

i3-msg workspace 4:SCHEDULE
i3-msg exec "google-chrome --new-window "https://calendar.google.com/calendar/render#main_7%7Cday""

sleep 1

i3-msg workspace 5:BANWEB
i3-msg exec "google-chrome --new-window "banweb.pdx.edu""

sleep 1
i3-msg exec "~/.bin/scripts/check_and_run_mcecs_vpn"
