#!/bin/bash

# Choose from my shifts to run, or exit
# Script by Nick Gilbert (nickgilbert2@gmail.com)
# Use and modify as you will

choices="Tutor Shift\nDeskShift\n"
selection=$( echo -e "$choices" | rofi  -dmenu  \
                                        -i \
                                        -hide-scrollbar true \
                                        -lines 2 \
                                        -p "Choose shift")

case $selection in
    "Tutor Shift")
        ~/.bin/scripts/shift-tutor
        break
        ;;
    "Desk Shift")
        ~/.bin/scripts/shift-desk
        break
        ;;
    *)
        echo "Invalid option";;
esac
