#!/bin/bash

# Takes in a directory and a timing (in seconds) and changes the wallpaper
# to a random image in that directory every so often

# uses pywal

clear

dir=${1:-~/Wallpapers}
if ! [ -d "$dir" ] ; then
    echo "Invalid dir!"
    notify-send "Invalid dir!"
    exit
fi

time=${2:-600}

if ! [[ $time =~ ^[0-9]+$ ]] ; then
    echo "Invalid timing!"
    notify-send "Invalid time set, must be a full number!"
    exit
fi

let "timeformat=$time / 60"
title="$dir, ${timeformat} min rotation - wal-timed"
#echo -e "\033]0;wal-timed\007" # sets the title to "wal-timed"
echo -e "\033]0;$title\007" # sets the title to "wal-timed"

x=0
while true ; do
    while [ $x -lt $time ] ; do
        sleep 1
        let "remain=$time-$x"
        let "secs=$remain % 60"
        secs=$(printf "%02d" $secs)
        let "remain=$remain / 60"
        echo "${remain}:${secs} till next wallpaper"
        let "x+=1"
    done
    x=0
    wal -i $dir -o ~/.bin/scripts/wal-set > out.tmp
    curr=$(head -n 1 out.tmp | rev | cut -d '/' -f 1 | rev)
    title="$dir, $curr, ${timeformat} min rotation - wal-timed"
    echo -e "\033]0;$title\007" # sets the title to "wal-timed"
done
