#!/bin/bash

# Wallpaper selector using rofi and pywal
# Also using my random wallpaper walgrab script


choices=$(ls ~/Wallpapers | tr ' ' '\n')
choices="Random\n$choices"

selection=$(echo -e "$choices" | rofi   -dmenu \
                                        -mesg "Set the wallpaper and associated color scheme" \
                                        -i \
                                        -p "Wallpaper:")

if [[ "$choices" != *"$selection"*  ]] ; then
    notify-send "No wallpaper selected"
elif [[ "$selection" == "Random" ]] ; then
    notify-send "Random wallpaper has been set as the theme"
    ~/.bin/scripts/walgrab
elif [[ "$selection" != "" ]] ; then
    selection="$HOME/Wallpapers/$selection"
    wal -i "$selection" -o ~/.bin/scripts/wal-set
fi

