#!/bin/bash

# Wallpaper selector using rofi and pywal
# Also using my random wallpaper walgrab script

if [ "$#" -ne 1 ] ; then
    dir=~/Wallpapers
else
    dir=$1
fi



choices=$(ls -F $dir | grep -v / | tr ' ' '\n')
choices="Random\n$choices"

selection=$(echo -e "$choices" | rofi   -dmenu \
                                        -mesg "Set the wallpaper and associated color scheme" \
                                        -i \
                                        -columns 2 \
                                        -p "Wallpaper:")
if [ -z "$selection" ] ; then
    notify-send "No wallpaper selected"
elif [ -d "$dir/$selection" ] ; then
    ~/.bin/scripts/walselect $dir/$selection
elif [[ "$choices" != *"$selection"* ]] ; then
    notify-send "No wallpaper selected"
elif [[ "$selection" == "Random" ]] ; then
    notify-send "Random wallpaper has been set as the theme"
    wal -i "$dir" -o ~/.bin/scripts/wal-set
elif [[ "$selection" != "" ]] ; then
    selection="$dir/$selection"
    wal -i "$selection" -o ~/.bin/scripts/wal-set
fi

